# CONFIG_FILE="/home/v-hengyuliu/mmclassification/configs/resnet/resnet101_b32x8_imagenet.py"
CONFIG_FILE="/home/v-hengyuliu/mmclassification/configs/resnet/resnet18_b16x8_cifar10.py"
GPU_NUM=8
seed=1

# bash ./tools/dist_train.sh ${CONFIG_FILE} ${GPU_NUM} --seed ${seed} --deterministic 

CONFIG_FILE="/home/v-hengyuliu/mmclassification/configs/resnet/resnet18_b16x8_cifar10.py"
optimizer=(
    # "{'type':'NormalLearnRate','lr':0.1,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':1,'optm_type':'NormalLearnRate_SampleLevel'}"
    # "{'type':'NormalLearnRate','lr':0.07,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':1,'optm_type':'NormalLearnRate_SampleLevel'}"
    # "{'type':'NormalLearnRate','lr':0.07,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':0.95,'normal_beta':1,'optm_type':'NormalLearnRate_SampleLevel'}"
    # "{'type':'NormalLearnRate','lr':0.049,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':1,'optm_type':'NormalLearnRate_SampleLevel'}"
    # "{'type':'NormalLearnRate','lr':0.049,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':0.95,'normal_beta':1,'optm_type':'NormalLearnRate_SampleLevel'}"
    # "{'type':'NormalLearnRate','lr':0.034,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':1,'optm_type':'NormalLearnRate_SampleLevel'}"
    # "{'type':'NormalLearnRate','lr':0.034,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':0.95,'normal_beta':1,'optm_type':'NormalLearnRate_SampleLevel'}"
    # "{'type':'NormalLearnRate','lr':0.023,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':1,'optm_type':'NormalLearnRate_SampleLevel'}"
    # "{'type':'NormalLearnRate','lr':0.01,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':0,'optm_type':'NormalLearnRate_SampleLevel'}"
    # "{'type':'NormalLearnRate','lr':0.01,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':0.9,'normal_beta':1.2,'optm_type':'NormalLearnRate_SampleLevel'}"
    # "{'type':'NormalLearnRate','lr':0.01,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':0.9,'normal_beta':1.1,'optm_type':'NormalLearnRate_SampleLevel'}"
    # "{'type':'NormalLearnRate','lr':0.01,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':0.9,'normal_beta':1,'optm_type':'NormalLearnRate_SampleLevel'}"
    # "{'type':'NormalLearnRate','lr':0.01,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':0.9,'normal_beta':0.9,'optm_type':'NormalLearnRate_SampleLevel'}"
    # "{'type':'NormalLearnRate','lr':0.01,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':0.9,'normal_beta':0.8,'optm_type':'NormalLearnRate_SampleLevel'}"
    # "{'type':'NormalLearnRate','lr':0.01,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':1,'optm_type':'NormalLearnRate_SampleLevel'}"
    # "{'type':'NormalLearnRate','lr':0.01,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':0.95,'normal_beta':1,'optm_type':'NormalLearnRate_SampleLevel'}"
    # "{'type':'NormalLearnRate','lr':0.01,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':0.85,'normal_beta':1,'optm_type':'NormalLearnRate_SampleLevel'}"
    # "{'type':'NormalLearnRate','lr':0.01,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':0.8,'normal_beta':1,'optm_type':'NormalLearnRate_SampleLevel'}"
    # "{'type':'NormalLearnRate','lr':0.1,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':0,'optm_type':'NormalLearnRate_SampleLevel'}"
    # "{'type':'NormalLearnRate','lr':0.1,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':2.4,'optm_type':'NormalLearnRate_SampleLevel'}"
    # "{'type':'NormalLearnRate','lr':0.1,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':2.2,'optm_type':'NormalLearnRate_SampleLevel'}"
    # "{'type':'NormalLearnRate','lr':0.1,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':2,'optm_type':'NormalLearnRate_SampleLevel'}"
    # "{'type':'NormalLearnRate','lr':0.1,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':1.8,'optm_type':'NormalLearnRate_SampleLevel'}"
    # "{'type':'NormalLearnRate','lr':0.1,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':1.6,'optm_type':'NormalLearnRate_SampleLevel'}"
    # "{'type':'NormalLearnRate','lr':0.1,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':1.4,'optm_type':'NormalLearnRate_SampleLevel'}"
    # "{'type':'NormalLearnRate','lr':0.1,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':1.2,'optm_type':'NormalLearnRate_SampleLevel'}"
    # "{'type':'NormalLearnRate','lr':0.1,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':1,'optm_type':'NormalLearnRate_SampleLevel'}"
    # "{'type':'NormalLearnRate','lr':0.1,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':0.8,'optm_type':'NormalLearnRate_SampleLevel'}"
    # "{'type':'NormalLearnRate','lr':0.1,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':0.6,'optm_type':'NormalLearnRate_SampleLevel'}"
    # "{'type':'NormalLearnRate','lr':0.1,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':0.4,'optm_type':'NormalLearnRate_SampleLevel'}"
    # "{'type':'NormalLearnRate','lr':0.2595769,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':0,'optm_type':'NormalLearnRate_SampleLevel'}"
    "{'type':'NormalLearnRate','lr':0.1,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':0,'optm_type':'NormalLearnRate_SampleLevel'}"
    "{'type':'NormalLearnRate','lr':0.1,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':1,'optm_type':'NormalLearnRate_SampleLevel'}"
    "{'type':'NormalLearnRate','lr':0.1,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':1.5,'optm_type':'NormalLearnRate_SampleLevel'}"
    "{'type':'NormalLearnRate','lr':0.1,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':2,'optm_type':'NormalLearnRate_SampleLevel'}"
    "{'type':'NormalLearnRate','lr':0.1,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':2.5,'optm_type':'NormalLearnRate_SampleLevel'}"
    "{'type':'NormalLearnRate','lr':0.1,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':3,'optm_type':'NormalLearnRate_SampleLevel'}"
    "{'type':'NormalLearnRate','lr':0.1,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':3.5,'optm_type':'NormalLearnRate_SampleLevel'}"
    "{'type':'NormalLearnRate','lr':0.1,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':4,'optm_type':'NormalLearnRate_SampleLevel'}"
    "{'type':'NormalLearnRate','lr':0.1,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':4.5,'optm_type':'NormalLearnRate_SampleLevel'}"
    "{'type':'NormalLearnRate','lr':0.1,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':5,'optm_type':'NormalLearnRate_SampleLevel'}"
    "{'type':'NormalLearnRate','lr':0.1,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':5.5,'optm_type':'NormalLearnRate_SampleLevel'}"
    "{'type':'NormalLearnRate','lr':0.1,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':6,'optm_type':'NormalLearnRate_SampleLevel'}"
    "{'type':'NormalLearnRate','lr':0.1,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':6.5,'optm_type':'NormalLearnRate_SampleLevel'}"
    "{'type':'NormalLearnRate','lr':0.1,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':7,'optm_type':'NormalLearnRate_SampleLevel'}"
    "{'type':'NormalLearnRate','lr':0.1,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':7.5,'optm_type':'NormalLearnRate_SampleLevel'}"
    "{'type':'NormalLearnRate','lr':0.1,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':8,'optm_type':'NormalLearnRate_SampleLevel'}"
    "{'type':'NormalLearnRate','lr':0.1,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':8.5,'optm_type':'NormalLearnRate_SampleLevel'}"
    "{'type':'NormalLearnRate','lr':0.1,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':9,'optm_type':'NormalLearnRate_SampleLevel'}"
    "{'type':'NormalLearnRate','lr':0.1,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':9.5,'optm_type':'NormalLearnRate_SampleLevel'}"
    "{'type':'NormalLearnRate','lr':0.1,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':10,'optm_type':'NormalLearnRate_SampleLevel'}"
    "{'type':'NormalLearnRate','lr':0.15,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':0,'optm_type':'NormalLearnRate_SampleLevel'}"
    "{'type':'NormalLearnRate','lr':0.2,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':0,'optm_type':'NormalLearnRate_SampleLevel'}"
    "{'type':'NormalLearnRate','lr':0.25,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':0,'optm_type':'NormalLearnRate_SampleLevel'}"
    "{'type':'NormalLearnRate','lr':0.3,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':0,'optm_type':'NormalLearnRate_SampleLevel'}"
    "{'type':'NormalLearnRate','lr':0.35,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':0,'optm_type':'NormalLearnRate_SampleLevel'}"
    "{'type':'NormalLearnRate','lr':0.4,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':0,'optm_type':'NormalLearnRate_SampleLevel'}"
    "{'type':'NormalLearnRate','lr':0.45,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':0,'optm_type':'NormalLearnRate_SampleLevel'}"
    "{'type':'NormalLearnRate','lr':0.5,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':0,'optm_type':'NormalLearnRate_SampleLevel'}"
    "{'type':'NormalLearnRate','lr':0.55,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':0,'optm_type':'NormalLearnRate_SampleLevel'}"
    "{'type':'NormalLearnRate','lr':0.6,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':0,'optm_type':'NormalLearnRate_SampleLevel'}"
    "{'type':'NormalLearnRate','lr':0.65,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':0,'optm_type':'NormalLearnRate_SampleLevel'}"
    "{'type':'NormalLearnRate','lr':0.7,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':0,'optm_type':'NormalLearnRate_SampleLevel'}"
    "{'type':'NormalLearnRate','lr':0.75,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':0,'optm_type':'NormalLearnRate_SampleLevel'}"
    "{'type':'NormalLearnRate','lr':0.8,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':0,'optm_type':'NormalLearnRate_SampleLevel'}"
    "{'type':'NormalLearnRate','lr':0.85,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':0,'optm_type':'NormalLearnRate_SampleLevel'}"
    "{'type':'NormalLearnRate','lr':0.9,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':0,'optm_type':'NormalLearnRate_SampleLevel'}"
    "{'type':'NormalLearnRate','lr':0.95,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':0,'optm_type':'NormalLearnRate_SampleLevel'}"
    "{'type':'NormalLearnRate','lr':0.1,'momentum':0.9,'weight_decay':0.0001,'normal_alpha':1,'normal_beta':0,'optm_type':'NormalLearnRate_SampleLevel'}"
)
for idx in ${optimizer[@]}
do
    bash ./tools/dist_train.sh ${CONFIG_FILE} ${GPU_NUM} --seed ${seed} --deterministic --cfg-options optimizer=$idx 
done



